spring:
  cloud:
    gateway:
      routes:
      - id: products-service
        uri: lb://products-service
        predicates:
          - Path=/api/products/**
        filters:
          - StripPrefix=2
      - id: items-service
        uri: lb://items-service
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2  